# Generated by Django 4.2.12 on 2024-05-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_comments_post_delete_comment_delete_show_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_content',
            field=models.TextField(default='New Post'),
        ),
    ]
