# Generated by Django 4.2.12 on 2024-07-19 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_post_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='sentiment_label',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='sentiment_score',
        ),
    ]
