# Generated by Django 4.2.12 on 2024-12-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_remove_order_user_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='usertype',
            field=models.CharField(choices=[('owner', 'Book Owner'), ('seeker', 'Book Seeker')], default='seeker', max_length=10),
        ),
    ]
