# Generated by Django 4.2.12 on 2024-12-13 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0032_profile_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the book title', max_length=255)),
                ('author', models.CharField(help_text='Enter the book author', max_length=255)),
                ('genre', models.CharField(help_text='Enter the genre of the book', max_length=255)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Good', 'Good'), ('Fair', 'Fair')], help_text='Select the condition of the book (New, Good, Fair)', max_length=50)),
                ('location', models.TextField(help_text='Enter the location of the book owner')),
                ('photo_url', models.ImageField(blank=True, help_text='Upload an image of the book', null=True, upload_to='book_photos/')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Not Available', 'Not Available')], default='Available', help_text='Select the status of the book (Available, Reserved, Not Available)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the book was added')),
                ('book_url', models.URLField(blank=True, help_text='Enter an optional link to the book (Amazon, Daraz, etc.)', max_length=500, null=True)),
                ('owner', models.ForeignKey(help_text='The user who owns the book', on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
