# Generated by Django 4.2.12 on 2024-12-13 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0033_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the request was made')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', help_text='The status of the request', max_length=50)),
                ('book', models.ForeignKey(help_text='The book being requested', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='myapp.books')),
                ('owner', models.ForeignKey(help_text='The user who owns the book', on_delete=django.db.models.deletion.CASCADE, related_name='owner_requests', to=settings.AUTH_USER_MODEL)),
                ('seeker', models.ForeignKey(help_text='The user who is requesting the book', on_delete=django.db.models.deletion.CASCADE, related_name='seeker_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
