# Generated by Django 4.2.12 on 2024-12-13 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0034_bookrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.TextField(help_text='The content of the message')),
                ('sent_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the message was sent')),
                ('book', models.ForeignKey(blank=True, help_text='Optional: Book associated with the message', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='myapp.books')),
                ('receiver', models.ForeignKey(help_text='The user receiving the message', on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(help_text='The user sending the message', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
